### ISSUE TITLE
expect_death

### ISSUE THREAD

**Issue by rianquinn** [boost-experimental/ut#104]
Any plans on adding an expect_death test? One feature that I need badly is the ability to test for std::terminate() and continue on, and I am not sure how to best approach that as throwing from a std::terminate() handler is not an option when a function is marked as noexcept.

**Comment by krzysztof-jusiak** [comment]
Sure, most likely it will be something like that

```
expect(death([]{ ... }); 
```

so that the expression might be compound with other expressions :+1:

**Comment by rianquinn** [comment]
That would be perfect. I know that Google Test has EXPECT_DEATH, so this syntax would be in sync with that. This would be a huge help as testing std::terminate() is a real pain without this. I think that Google Test implements this feature using a fork/wait. Basically, it forks, and the parent waits for the child to exit, and checks the status.

**Comment by rianquinn** [comment]
Here is a possible implementation:
https://github.com/catchorg/Catch2/issues/553#issuecomment-164483727
