### ISSUE TITLE
Allow default runner to run and reporting on unit tests before exit()

### ISSUE THREAD

**Issue by OskarLinde** [boost-experimental/ut#239]
There are a number of cases when you want unit tests to run earlier than the program exits. E.g. an application may want to run and report failing unit tests on startup. While this is doable with a custom runner, it should be fairly straightforward to add a method to replicate the default runner's destructor behavior. Something that effectively allows:

```c++
    int main(int argc, char **argv)
    {
        boost::ut::cfg<>.run();                            // (1)
        boost::ut::cfg<>.on(boost::ut::events::summary{}); // (2) currently not accessible
        ...
```
Possible APIs could be a `bool run_and_report()` method to replicate the current destructor functionality or more flexible a `void report_summary()` to just do (2).

**Comment by krzysztof-jusiak** [comment]
Thanks @OskarLinde, good point :+1: 

Should be fixed by https://github.com/boost-experimental/ut/commit/8811bd5c1e7f8c26fe45c20cc047ffb93ab89159

Example usage:
```
int main() {
  const auto result = ut::cfg<>.run({.report_errors = true});
  std::cout << "After report\n";
  return result;
}
```

**Comment by OskarLinde** [comment]
Thanks for amazingly quick fix. Just tested it; works as advertised. 👍
