### ISSUE TITLE
Add CMake Interface Library

### ISSUE THREAD

**Issue by athrun22** [boost-experimental/ut#258]
I am very interested in using your library. I would like to use ```FetchContent``` and have access to your library through ```add_subdirectory```. However, your library does not create a convenience target to use with ```target_link_libraries```. While it is little effort for me to add the necessary include directory myself, I would much rather just "link" against your header only library like so:
```cmake
target_link_libraries(MyTarget PRIVATE Boost::ut)
```
I have included an import prefix to mirror Boost's component linking behavior.
Defining an *interface* library through CMake with the appropriate include directories will make this possible.
The changes might look like the following.
```cmake
add_library(ut INTERFACE)
add_library(Boost::ut ALIAS ut)
target_include_directories(ut INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>)
```
This code also paves the way for the interface target to be exported and included with ```find_package```.

**Comment by krzysztof-jusiak** [comment]
Thanks, @athrun22, it should be fixed now, let me know if it works for you :thinking:

**Comment by athrun22** [comment]
@krzysztof-jusiak, thanks! The interface library works perfectly 😃😃😃
