### ISSUE TITLE
Microbenchmarking

### ISSUE THREAD

**Issue by jwillikers** [boost-experimental/ut#276]
Would it be possible to support creating microbenchmarks? It is not uncommon for test frameworks to incorporate microbenchmark support. Below are a couple of frameworks I'm aware of which closely tie microbenchmarking and unit testing.
1.   Catch2 implements microbenchmarks -> https://github.com/catchorg/Catch2/blob/master/docs/benchmarks.md#top
1.   Google Benchmark (related to Google Test) is a simple, macro-based solution -> https://github.com/google/benchmark
1.   The **go** programming language implements microbenchmarking as a part of its built-in testing framework -> https://golang.org/pkg/testing/

I'm not aware of any libraries for benchmarking C++ code that are macro-free, and I figure I'm not the only one that would have a similar interest in macro-free microbenchmarking.

**Comment by krzysztof-jusiak** [comment]
Yeah, potentially we could some benchmarking primitives, let me think about it some more not to overblow the UT. Let's keep that issue open for the time being to track the issue, thanks @jwillikers :+1:

**Comment by data-man** [comment]
[nanobench](https://github.com/martinus/nanobench) is very good.
