### ISSUE TITLE
Build errors on Visual Studio with clang-cl compiler when using boost.ut's CMakeLists.txt

### ISSUE THREAD

**Issue by claremacrae** [boost-experimental/ut#277]
## Expected Behavior

Boost.ut builds and tests pass with VS2019 MSVC with clang-cl compiler

I know this, as we have been building that with the Approval Tests integration, which works file with this compiler.

## Actual Behavior

Builds fail, with the error:

```
  Building Custom Rule D:/a/ApprovalTests.cpp.Builds/ApprovalTests.cpp.Builds/_deps/ut-src/example/CMakeLists.txt
clang-cl : error : unknown argument ignored in clang-cl: '-pedantic' [-Werror,-Wunknown-argument] [D:\a\ApprovalTests.cpp.Builds\ApprovalTests.cpp.Builds\_deps\ut-build\example\BDD.vcxproj]
clang-cl : error : unknown argument ignored in clang-cl: '-pedantic-errors' [-Werror,-Wunknown-argument] [D:\a\ApprovalTests.cpp.Builds\ApprovalTests.cpp.Builds\_deps\ut-build\example\BDD.vcxproj]
```

For an example failure, see https://github.com/claremacrae/ApprovalTests.cpp.Builds/runs/370748554

## Steps to Reproduce the Problem

  1. cmake -G "Visual Studio 16 2019" -T "clangcl"
  1. build all of Boost.ut, including examples

## Specifications

  - Version: 8004290d195b08eda531eb015ddcda2e11d41ce9
  - Platform: 'The CXX compiler identification is Clang 9.0.0 with MSVC-like command-line'
  - Subsystem: ?

## Nature of fix

See https://github.com/approvals/ApprovalTests.cpp/blob/v.7.0.0/tests/UT_Tests/CMakeLists.txt#L17 for the type of check to use...

Someone previously reported this problem with ApprovalTests.cpp on this environment, and provided a fix which used windows-style compiler warnings if using clang-cl...

**Comment by claremacrae** [comment]
I just realised that this is showing a build failure in my use of Boost.ut, rather than the actual Boost.ut tests not running...

For more info, in this build I am testing the building of Approval Tests code using Boost.ut via `FetchContent()`, and in this case, Boost.ut is modifying the compiler options for all targets, not just for its own tests - by using `add_compile_options()`

And as far as I can see, that modification is not valid for clang-cl, so breaks builds for any targets on that platform...

**Comment by athrun22** [comment]
@claremacrae ```FetchContent``` can isolate the effects of a ```add_compile_options``` and similar commands that effect *directory properties* by adding subdirectories where dependencies are made available.

Your dependencies [CMakeLists.txt](https://github.com/claremacrae/ApprovalTests.cpp.Builds/blob/master/dependencies/CMakeLists.txt) could do something similar to the following.

```cmake
if (APPROVAL_TESTS_BUILDS_USE_BOOST_UT)
    FetchContent_Declare(ut
            GIT_REPOSITORY https://github.com/boost-experimental/ut.git
            GIT_TAG 8004290d195b08eda531eb015ddcda2e11d41ce9)
    # Isolate the effects of directory properties by making Boost ut available in a sub-directory.
    add_subdirectory(ut)
endif(APPROVAL_TESTS_BUILDS_USE_BOOST_UT)
```

The CMakeListst.txt in the *ut* subdirectory would look like this:
```cmake
FetchContent_MakeAvailable(ut)
```

**Comment by claremacrae** [comment]
Thanks @athrun22 - I'll read up on CMake scopes...

I believe that this issue will also prevent Boost.ut itself from building on clang-cl, so would still be worth addressing.

**Comment by athrun22** [comment]
Under most circumstances, it is recommended to use the ```target_***``` CMake commands which only effect specific targets as opposed to directory-level commands. I use a **lot** of specific compiler flags for test cases for my header-only libraries and use an internal interface library to only have to write these flags once. I threw together a quick example below to make this easier to understand.
```cmake
add_library(my-project-test-interface INTERFACE)
# I use an alias library to be safer
add_library(my-project::test-interface ALIAS my-project-test-interface)
target_compile_options(my-project-test-interface INTERFACE $<$<CMAKE_CXX_COMPILER:Clang>:-Weverything -Wno-c++98-compat> $<$<CMAKE_CXX_COMPILER:GNU>:-Wall>)
add_executable(my-test)
target_link_libraries(my-test PRIVATE my-project::test-interface)
```

**Comment by athrun22** [comment]
@claremacrae The CMake documentation has never been quite enough for me since I do extensive CMake work. I can't recommend [Professional CMake](https://crascit.com/professional-cmake/) by Craig Scott enough! It has a section on CMake scopes and a section on ```FetchContent```. And shout out to [CPPCast](cppcast.com) for helping me find his book, your ApprovalTests library, and Boost ut.  🤯

**Comment by krzysztof-jusiak** [comment]
Thank you @jwillikers, @claremacrae. I'll take a look this week and fix the issues, thanks again :+1:

**Comment by krzysztof-jusiak** [comment]
Should be fixed in the newest master :+1:
