### ISSUE TITLE
Disable Running Tests automatically

### ISSUE THREAD

**Issue by jwillikers** [boost-experimental/ut#280]
Would it be possible to disable tests running as part of the build? It makes it difficult to incorporate this project as sub-build when failing tests block building the rest of the project. It would be nice to be able to then run all of the tests with a CTest invocation after the build step.

**Comment by claremacrae** [comment]
I’d really appreciate that.

**Comment by krzysztof-jusiak** [comment]
:thinking: With the assumption that the library is well tested the integration might be done with `BUILD_TESTS=OFF`. I personally believe that building and running tests is the thing (for example static_asserts tests). But I agree it's annoying to integrate if tests aren't passing in any env and that should be addressed IMHO by finding and fixing the root cause :thinking:

**Comment by jwillikers** [comment]
1.  One of the simplest examples of why it might be preferred to have all the tests run as their own step is that more information can be gleaned from the results of multiple tests. If tests stop running after the first failed test, you get less information.

1.  Consumers of your library may be on a time-crunch where they just need to build their project, ensure that a single failing test in your library is non-serious, and move on to their primary task at the moment. Of course, you have to hope they will take the time later to submit an issue. 😅

1.  Last, CMake splits building and testing into separate steps as seen in [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html#external-project-definition). CMake typically prefers running tests after building a project through the use of its [CTest/CDash](https://cmake.org/cmake/help/latest/manual/ctest.1.html#manual:ctest(1)) functionality which can additionally handle submitting test results to CI dashboards.
