### ISSUE TITLE
CMake Variable Name Collisions & Cache Pollution

### ISSUE THREAD

**Issue by jwillikers** [boost-experimental/ut#304]
Several CMake options are likely to cause name collisions with similarly named variables, and variables are put into the CMake cache without consideration for parent projects.

Variables such as `BUILD_TESTS` are usually prefixed with the project's name to avoid potential name collisions.
An example for [Boost].µT is `UT_BUILD_TESTS`.

Projects incorporating [Boost].µT may wish to not have certain [Boost].µT-specific variables shown in the cache, like the `BUILD_TESTS` option.
Best practice is to use a non-cache variable as this leaves the decision up to parent projects whether to make those variables available in the cache or not.
A common idiom used for testing is to automatically include the tests if the project is the top-level project or if the appropriate variable is enabled.
The example below demonstrates this behavior.
```cmake
if(TEST_UT OR CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  add_subdirectory(test)
endif()
```
There is no call to the `option()` command, i.e.
`option(TEST_UT "Enable building the tests" yes)`, as this populates the variable in the CMake cache.

**Comment by krzysztof-jusiak** [comment]
Would love some help with it from some CMake experts, please :pray:

**Comment by jwillikers** [comment]
I can work on a PR 👍

**Comment by krzysztof-jusiak** [comment]
Thank you @jwillikers, that will be greatly appreciated :)

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-experimental/ut/pull/340
