### ISSUE TITLE
Visual C++ Compiler Error C2326 using Constexpr Array from Lambda in a Test Case in a Throws Assertion

### ISSUE THREAD

**Issue by jwillikers** [boost-experimental/ut#306]
## Expected Behavior
A function with a `throws` / `nothrow` assertion should compile with the Visual C++ Compiler when given a lambda which uses a `constexpr` `std::array` variable... right? This is a *very* specific issue 😩 
```cpp
#include <array>
#include <boost/ut.hpp>

int main() {
  using namespace boost::ut;
  "example_test"_test = [] {
    constexpr std::array<int, 1> i{{10}};
    expect(nothrow([] { return i.front(); }));
  };
}
```

It is also interesting to note this only occurs in a test case and not when used directly from `main`, hence the following compiles:
```cpp
#include <array>
#include <boost/ut.hpp>

int main() {
  using namespace boost::ut;
  expect(nothrow([] {
    constexpr std::array<int, 1> i{{10}};
    return i.front();
  }));
}
```

Using a constexpr `int` instead of a `std::array` also compiles:
```cpp
#include <boost/ut.hpp>

int main() {
  using namespace boost::ut;
  "example_test"_test = [] {
    constexpr int i{10};
    expect(nothrow([] { return i; }));
  };
}
```

Perhaps this is a bug in the MSVC compiler?
 
## Actual Behavior
Error C2326 is given stating that the lambda function cannot access the constexpr variable.

I can workaround this issue by putting the constexpr variable within the lambda itself, as follows:
```cpp
#include <array>
#include <boost/ut.hpp>

int main() {
  using namespace boost::ut;
  "example_test"_test = [] {
    expect(nothrow([] {
      constexpr std::array<int, 1> i{{10}};
      return i.front();
    }));
  };
}
```

## Steps to Reproduce the Problem

Compiling the preceding snippets above using C++20 / MSVC 16.4.4 should showcase the error.
By the way, Clang compiles the problematic code just fine.

## Specifications

  - Version: 1.1.6
  - Platform: Windows
  - Subsystem: MSVC 16.4.4

**Comment by krzysztof-jusiak** [comment]
Hmm, isn't the case that you are just missing the capture of `i`?

The following works just fine with MSVC :+1: 

```cpp
int main() {
  using namespace boost::ut;
  "example_test"_test = [] {
    constexpr std::array<int, 1> i{10};
    expect(nothrow([i] { return i.front(); }));
  };
}
```

Full example -> https://godbolt.org/z/PMYVyk

Alternatively, you can make it static too if it's constant :thinking: 

```cpp
int main() {
  using namespace boost::ut;
  "example_test"_test = [] {
    static constexpr std::array<int, 1> i{10};
    expect(nothrow([] { return i.front(); }));
  };
}
```

Full example -> https://godbolt.org/z/TVJJPE

Please let me know if I misunderstood your issue, thanks @jwillikers :+1:

**Comment by jwillikers** [comment]
Thanks @krzysztof-jusiak. I must have some misunderstanding of lambda captures here. Why does your first example work given `i` explicitly in the capture but not work when using the generic `=` or `&` captures?

**Comment by krzysztof-jusiak** [comment]
Capturing using `=` should work as well and it does in `gcc/clang`, so it seems like MSVC issue :bug: 
 * https://godbolt.org/z/dB6J4n

**Comment by jwillikers** [comment]
@krzysztof-jusiak Thanks for your help! I found a bug report for the Visual C++ Compiler [here](https://developercommunity.visualstudio.com/content/problem/857960/lambda-does-not-capture-some-constexpr-variables-w.html) which seems to capture this issue and it looks like the fix is complete and will be in an upcoming release. Thanks again for all your help 😀😀😀

**Comment by krzysztof-jusiak** [comment]
Nice @jwillikers, thanks for following it up and the link :+1:
