### ISSUE TITLE
Non-Type Template Parameters causes compilation error with g++-10

### ISSUE THREAD

**Issue by furkanusta** [boost-experimental/ut#329]
## Specifications

  - Version: gcc 10.0.1 (20200327)
  - Platform: Linux - Centos 7

## Error Message

> ../example/tmp.cpp:19:12: error: 'boost::ut::v1_1_7::detail::eq_<boost::ut::v1_1_7::detail::integral_constant<42>, int>' is not a valid type for a template non-type parameter because it is not structural
>    19 |     expect(constant<42_i == i> and type<void> == type<void> and
>       |            ^~~~~~~~~~~~~~~~~~~
> In file included from ../example/tmp.cpp:8:
> ../include/boost/ut.hpp:738:14: note: 'boost::ut::v1_1_7::detail::eq_<boost::ut::v1_1_7::detail::integral_constant<42>, int>::lhs_' is not public
>   738 |   const TLhs lhs_{};
>       |              ^~~~
> 

en.cppreference.com states, for non-type template parameters
 a literal class type with the following properties: 
- all base classes and non-static data members are public and non-mutable and
- the types of all bases classes and non-static data members are structural types or (possibly multi-dimensional) array thereof. 

As a workaround, I've commented the ifdefs for Constant in line 2190

**Comment by krzysztof-jusiak** [comment]
Thanks, @furkanusta, It's fixed now -> https://godbolt.org/z/p6mhZR
