### ISSUE TITLE
[Question]: What is the reason for the user defined literals?

### ISSUE THREAD

**Issue by rianquinn** [boost-experimental/ut#89]
In the following example:
```
"args"_test =
   [](const auto& arg) {
      expect(arg >= 1_i);
    }
  | std::vector{1, 2, 3};
```

You use a custom integer literal. Why? I noticed there is afair amount of code in the library to support this so I was just curious what its purpose is as it works fine without the literals.

**Comment by krzysztof-jusiak** [comment]
Mainly, in order to nicely print error messages with expanded expressions :+1: 

```
  expect(add(1, 2) == 4_i); // with UDL -> will nicely print the expression
  expect(add(1, 2) == 4); // without UDL -> will use bool
```

```
  <source>:8:FAILED [3 == 4]
  <source>:9:FAILED [false]
```

Example -> https://godbolt.org/z/4bauN2

**Comment by rianquinn** [comment]
:+1:
